SOUND_FILES = {
    'punch': 'sound/punch.wav',
    'kick': 'sound/kick.wav',
    'hit': 'sound/hit.wav',
    'button': 'sound/button.wav',
    'next_scene': 'sound/next_scene.wav',
    'mai_skill': 'sound/mai_skill.wav',
    'fight': 'sound/fight.wav',
    'kk_skill1': 'sound/kk_skill1.wav',
    'kk_skill2': 'sound/kk_skill2.wav',
    'ko': 'sound/ko.wav',
    'winner': 'sound/winner.wav',
    'kyo_skill': 'sound/kyo_skill.wav',
    'iori_skill1_ready': 'sound/iori_skill1_ready.wav',
    'iori_skill': 'sound/iori_skill.wav',
    'iori_ment': 'sound/iori_ment.wav',
    'iori_victory': 'sound/iori_victory.wav',
}
